name: Validate OpenAPI

on:
  push:
    paths:
      - "openapi.yaml"
  pull_request:
    paths:
      - "openapi.yaml"

jobs:
  lintspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            openapi.yaml
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint OpenAPI with Redocly
        run: npx --package @redocly/cli@latest redocly lint openapi.yaml

      - name: Lint OpenAPI with Spectral
        run: npx --package @stoplight/spectral-cli spectral lint openapi.yaml

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install yamllint
        run: pip install yamllint

      - name: Yamllint
        run: yamllint openapi.yaml

  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check python/remotebmi

  r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
        working-directory: R/remotebmi
      - uses: r-lib/actions/check-r-package@v2
        working-directory: R/remotebmi