name: R

on:
  push:
    paths:
      - "R/remotebmi/**"
  pull_request:
    paths:
      - "R/remotebmi/**"

jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
        with:
          sparse-checkout: |
            R/remotebmi
      - name: Move R package to root
        run: shopt -s dotglob && mv R/remotebmi/* .
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
